maintainer       "YOUR_COMPANY_NAME"
maintainer_email "YOUR_EMAIL"
license          "All rights reserved"
description      "Installs/Configures base"
long_description ""
version          "0.0.1"

depends "git"
depends "build-essential"
depends "chef-client"